version: '3.4'

services:
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672"

  customer-microservice:
    container_name: customer-microservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "RabbitMqSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - rabbitmq
    ports:
      - "8085:80"
  product-microservice:
    container_name: product-microservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "RabbitMqSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - rabbitmq
    ports:
      - "8086:80"
  order-microservice:
    container_name: order-microservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "RabbitMqSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - rabbitmq
    ports:
      - "8087:80"
